# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://netlify-cms-react-starter.netlify.com # This url will display in the top-right of the CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: countries
    label: Pays
    editor:
      preview: true
    folder: content/countries
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Titre, name: title, widget: string}
      - {label: Sous-titre, name: subttitle, widget: string}
      - label: "Localisation"
        required: false
        name: "localisation"
        widget: "object"
        fields:
          - {label: Latitude, name: latitude, widget: number, required: false}
          - label: 'Nord ou Sud'
            name: 'northOrSouth'
            widget: 'select'
            options: ["N", "S"]
            default: 'N'
          - {label: Longitude, name: longitude, widget: number, required: false}
          - label: 'Est ou Ouest'
            name: 'eastOrWest'
            widget: 'select'
            options: ["E", "O"]
            default: 'E'
      - {label: Image de couverture, name: imageCover, widget: image, required: false}
      - label: 'Statut'
        name: 'status'
        widget: 'select'
        options: ["Publié", "Caché"]
        default: 'Publié'
      - {label: Content, name: body, widget: markdown}

  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Url, name: siteUrl, widget: string, required: false}
          - {label: Site Description, name: siteDescription, widget: text, required: false}
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - {label: Image, name: image, widget: image, required: false}
              - {label: Twitter Site Account, name: twitterSiteAccount, widget: string, required: false}
              - {label: Twitter Creator Account, name: twitterCreatorAccount, widget: string, required: false}
          - {label: Header Meta / Scripts, name: headerScripts, widget: text, required: false}
          - {label: Enable Service Worker Pre-Cache, name: enableServiceWorker, widget: boolean, required: false}

      - file: "content/settings/ui.yml"
        label: "UI"
        name: "ui"
        fields:
          - label: Top Bar
            name: topBar
            widget: object
            fields:
              - {label: Introduction (sans le 'Sauvage'), name: intro, widget: string}
              - label: Liens
                name: links
                widget: list
                fields: 
                  - {label: Libellé, name: label, widget: string}
                  - {label: Lien, name: link, widget: string}

  - name: "home"
    label: "Home"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/home/index.yml"
        label: "Home"
        name: "home"
        fields:
          - {label: Image de couverture, name: imageCover, widget: image, required: true}
          - label: Titres
            name: titles
            widget: object
            fields: 
              - label: Titre
                name: title
                widget: object
                fields:
                  - {label: Partie supérieur, name: top, widget: string, required: true}
                  - {label: Partie inférieur, name: bottom, widget: string, required: true}
              - {label: Sous-titre, name: subtitle, widget: string}